select algoID,nodeDataType,nodeID,avg(score) as avgscore into outfile '/tmp/prodigalscores/avg/1160'     fields terminated by ',' lines terminated by '\n' from resultScores where algoID = 1160 group by algoID, nodeID order by avgscore desc limit 10000;
select algoID,nodeDataType,nodeID,avg(score) as avgscore into outfile '/tmp/prodigalscores/avg/1161'     fields terminated by ',' lines terminated by '\n' from resultScores where algoID = 1161 group by algoID, nodeID order by avgscore desc limit 10000;
select algoID,nodeDataType,nodeID,avg(score) as avgscore into outfile '/tmp/prodigalscores/avg/1170'     fields terminated by ',' lines terminated by '\n' from resultScores where algoID = 1170 group by algoID, nodeID order by avgscore desc limit 10000;
select algoID,nodeDataType,nodeID,avg(score) as avgscore into outfile '/tmp/prodigalscores/avg/1171'     fields terminated by ',' lines terminated by '\n' from resultScores where algoID = 1171 group by algoID, nodeID order by avgscore desc limit 10000;
select algoID,nodeDataType,nodeID,avg(score) as avgscore into outfile '/tmp/prodigalscores/avg/1172'     fields terminated by ',' lines terminated by '\n' from resultScores where algoID = 1172 group by algoID, nodeID order by avgscore desc limit 10000;
select algoID,nodeDataType,nodeID,avg(score) as avgscore into outfile '/tmp/prodigalscores/avg/1190'     fields terminated by ',' lines terminated by '\n' from resultScores where algoID = 1190 group by algoID, nodeID order by avgscore desc limit 10000;
select algoID,nodeDataType,nodeID,avg(score) as avgscore into outfile '/tmp/prodigalscores/avg/1150'     fields terminated by ',' lines terminated by '\n' from resultScores where algoID = 1150 group by algoID, nodeID order by avgscore desc limit 10000;
select algoID,nodeDataType,nodeID,avg(score) as avgscore into outfile '/tmp/prodigalscores/avg/1151'     fields terminated by ',' lines terminated by '\n' from resultScores where algoID = 1151 group by algoID, nodeID order by avgscore desc limit 10000;
select algoID,nodeDataType,nodeID,avg(score) as avgscore into outfile '/tmp/prodigalscores/avg/1154'     fields terminated by ',' lines terminated by '\n' from resultScores where algoID = 1154 group by algoID, nodeID order by avgscore desc limit 10000;
select algoID,nodeDataType,nodeID,avg(score) as avgscore into outfile '/tmp/prodigalscores/avg/1173'     fields terminated by ',' lines terminated by '\n' from resultScores where algoID = 1173 group by algoID, nodeID order by avgscore desc limit 10000;
select algoID,nodeDataType,nodeID,avg(score) as avgscore into outfile '/tmp/prodigalscores/avg/1180'     fields terminated by ',' lines terminated by '\n' from resultScores where algoID = 1180 group by algoID, nodeID order by avgscore desc limit 10000;
select algoID,nodeDataType,nodeID,avg(score) as avgscore into outfile '/tmp/prodigalscores/avg/1181'     fields terminated by ',' lines terminated by '\n' from resultScores where algoID = 1181 group by algoID, nodeID order by avgscore desc limit 10000;
select algoID,nodeDataType,nodeID,avg(score) as avgscore into outfile '/tmp/prodigalscores/avg/103'      fields terminated by ',' lines terminated by '\n' from resultScores where algoID = 103 group by algoID, nodeID order by avgscore desc limit 10000;

select algoID,nodeDataType,nodeID,avg(score) as avgscore into outfile '/tmp/prodigalscores/avg/all'      fields terminated by ',' lines terminated by '\n' from resultScores group by nodeID order by avgscore desc limit 10000;

select algoID,nodeDataType,nodeID,max(score) as maxscore into outfile '/tmp/prodigalscores/max/1161'     fields terminated by ',' lines terminated by '\n' from resultScores where algoID = 1161 group by algoID, nodeID order by maxscore desc limit 10000;
select algoID,nodeDataType,nodeID,max(score) as maxscore into outfile '/tmp/prodigalscores/max/1170'     fields terminated by ',' lines terminated by '\n' from resultScores where algoID = 1170 group by algoID, nodeID order by maxscore desc limit 10000;
select algoID,nodeDataType,nodeID,max(score) as maxscore into outfile '/tmp/prodigalscores/max/1171'     fields terminated by ',' lines terminated by '\n' from resultScores where algoID = 1171 group by algoID, nodeID order by maxscore desc limit 10000;
select algoID,nodeDataType,nodeID,max(score) as maxscore into outfile '/tmp/prodigalscores/max/1172'     fields terminated by ',' lines terminated by '\n' from resultScores where algoID = 1172 group by algoID, nodeID order by maxscore desc limit 10000;
select algoID,nodeDataType,nodeID,max(score) as maxscore into outfile '/tmp/prodigalscores/max/1190'     fields terminated by ',' lines terminated by '\n' from resultScores where algoID = 1190 group by algoID, nodeID order by maxscore desc limit 10000;
select algoID,nodeDataType,nodeID,max(score) as maxscore into outfile '/tmp/prodigalscores/max/1150'     fields terminated by ',' lines terminated by '\n' from resultScores where algoID = 1150 group by algoID, nodeID order by maxscore desc limit 10000;
select algoID,nodeDataType,nodeID,max(score) as maxscore into outfile '/tmp/prodigalscores/max/1151'     fields terminated by ',' lines terminated by '\n' from resultScores where algoID = 1151 group by algoID, nodeID order by maxscore desc limit 10000;
select algoID,nodeDataType,nodeID,max(score) as maxscore into outfile '/tmp/prodigalscores/max/1154'     fields terminated by ',' lines terminated by '\n' from resultScores where algoID = 1154 group by algoID, nodeID order by maxscore desc limit 10000;
select algoID,nodeDataType,nodeID,max(score) as maxscore into outfile '/tmp/prodigalscores/max/1173'     fields terminated by ',' lines terminated by '\n' from resultScores where algoID = 1173 group by algoID, nodeID order by maxscore desc limit 10000;
select algoID,nodeDataType,nodeID,max(score) as maxscore into outfile '/tmp/prodigalscores/max/1180'     fields terminated by ',' lines terminated by '\n' from resultScores where algoID = 1180 group by algoID, nodeID order by maxscore desc limit 10000;
select algoID,nodeDataType,nodeID,max(score) as maxscore into outfile '/tmp/prodigalscores/max/1181'     fields terminated by ',' lines terminated by '\n' from resultScores where algoID = 1181 group by algoID, nodeID order by maxscore desc limit 10000;
select algoID,nodeDataType,nodeID,max(score) as maxscore into outfile '/tmp/prodigalscores/max/103'      fields terminated by ',' lines terminated by '\n' from resultScores where algoID = 103  group by algoID, nodeID order by maxscore desc limit 10000;

select algoID,nodeDataType,nodeID,max(score) as maxscore into outfile '/tmp/prodigalscores/max/all'      fields terminated by ',' lines terminated by '\n' from resultScores group by nodeID order by maxscore desc limit 10000;
