#include "alg_convert.h"
#include <stdlib.h>

#define TYPE(X) #X
const char * algtype_strings [] = {
  ALG_TYPES
};
#undef TYPE

int64_t DT_BLACKLIST 				= 1000; 
int64_t DT_BY_GROUP 				= 1001;
int64_t DT_EVENT_TIME 				= 1002;
int64_t DT_LDAP_GROUP 				= 1003;
int64_t DT_LOGON_CORRECTION			= 1004;
int64_t DT_SPARSE_VECTOR 			= 1005;
int64_t DT_MERGE_SCORES			        = 1006;
int64_t DT_UNSPARSE_VECTOR 			= 1007;
int64_t DT_EMAIL_TO_USER 			= 1008;
int64_t DT_EMAIL_SUMMARIZE 			= 1009;
int64_t DT_MERGESCORES_FLOW 			= 1020;
int64_t DT_MERGESCORES_DAY 			= 1021;
int64_t DT_MERGESCORES_WEEK 			= 1022;
int64_t DT_SIMPLE_STAT_SCORER 			= 1050;
int64_t DT_URL_FEATURES 			= 1100;
int64_t DT_URL_FEATURES_SCORE  			= 1101;
int64_t DT_LOGON_FEATURES 		 	= 1102;
int64_t DT_LOGON_FEATURES_SCORE			= 1104;
int64_t DT_PRINTER_FEATURES			= 1105;
int64_t DT_PRINTER_FEATURES_SCORE		= 1106;
int64_t DT_DEVICE_FEATURES 			= 1107;
int64_t DT_DEVICE_FEATURES_SCORE		= 1108;
int64_t DT_EMAIL_FEATURES 			= 1109;
int64_t DT_EMAIL_FEATURES_SCORE			= 1110;
int64_t DT_FILE_FEATURES 			= 1111;
int64_t DT_FILE_FEATURES_SCORE			= 1112;
int64_t DT_OTHER_FEATURE_SCORE			= 1115;
int64_t DT_URL_UPLOAD_SCORE			= 1150;
int64_t DT_URL_DOWNLOAD_SCORE			= 1151;
int64_t DT_URL_BLACKLIST_VISITS_SCORE		= 1152;
int64_t DT_URL_DISTINCT_BLACKLIST_SCORE		= 1153;
int64_t DT_URL_DOMAINS_PER_USER_SCORE		= 1154;
int64_t DT_LOGON_SCORE			        = 1160;
int64_t DT_LOGON_WORKSTATION_SCORE		= 1161;
int64_t DT_LOGON_ANOMALOUS_WORKSTATION_COUNT	= 1162;
int64_t DT_PRINTER_NUMBER_OF_JOBS_SCORE		= 1170;
int64_t DT_PRINTER_DISTINCT_PRINTER_SCORE	= 1171;
int64_t DT_PRINTER_WORKSTATION_SCORE		= 1172;  
int64_t DT_PRINTER_PER_USER_SCORE		= 1173;  
int64_t DT_EMAIL_RCVD_NUMBER_VIEWED_SCORE	= 1180;
int64_t DT_EMAIL_SENT_NUMBER_SENT_SCORE		= 1181;
int64_t DT_FILE_REMOVABLE_ACCESS_SCORE	        = 1190;
int64_t DT_FILE_REMOVABLE_COPY_TO_SCORE		= 1191;
int64_t DT_FILE_REMOVABLE_COPY_FROM_SCORE	= 1192;
int64_t DT_FILE_NUMBER_CREATED_SCORE	        = 1193;
int64_t DT_FILE_FOLDER_CREATED_SCORE	        = 1194;

int64_t *  dts_to_algs;
int64_t *  algs_to_dts;

void
init_algs_to_dts() {
  dts_to_algs = calloc(500, sizeof(int64_t));
  algs_to_dts = calloc(MAX_ALG_TYPE, sizeof(int64_t));

  dts_to_algs[DT_BLACKLIST-1000] = ALG_BLACKLIST;
  algs_to_dts[ALG_BLACKLIST] = DT_BLACKLIST;
  dts_to_algs[DT_BY_GROUP-1000] = ALG_BY_GROUP;
  algs_to_dts[ALG_BY_GROUP] = DT_BY_GROUP;
  dts_to_algs[DT_EVENT_TIME-1000] = ALG_EVENT_TIME;
  algs_to_dts[ALG_EVENT_TIME] = DT_EVENT_TIME;
  dts_to_algs[DT_LDAP_GROUP-1000] = ALG_LDAP_GROUP;
  algs_to_dts[ALG_LDAP_GROUP] = DT_LDAP_GROUP;
  dts_to_algs[DT_LOGON_CORRECTION-1000] = ALG_LOGON_CORRECTION;
  algs_to_dts[ALG_LOGON_CORRECTION] = DT_LOGON_CORRECTION;
  dts_to_algs[DT_SPARSE_VECTOR-1000] = ALG_SPARSE_VECTOR;
  algs_to_dts[ALG_SPARSE_VECTOR] = DT_SPARSE_VECTOR;
  dts_to_algs[DT_MERGE_SCORES-1000] = ALG_MERGE_SCORES;
  algs_to_dts[ALG_MERGE_SCORES] = DT_MERGE_SCORES;
  dts_to_algs[DT_UNSPARSE_VECTOR-1000] = ALG_UNSPARSE_VECTOR;
  algs_to_dts[ALG_UNSPARSE_VECTOR] = DT_UNSPARSE_VECTOR;
  dts_to_algs[DT_EMAIL_TO_USER-1000] = ALG_EMAIL_TO_USER;
  algs_to_dts[ALG_EMAIL_TO_USER] = DT_EMAIL_TO_USER;
  dts_to_algs[DT_EMAIL_SUMMARIZE-1000] = ALG_EMAIL_SUMMARIZE;
  algs_to_dts[ALG_EMAIL_SUMMARIZE] = DT_EMAIL_SUMMARIZE;
  dts_to_algs[DT_MERGESCORES_FLOW-1000] = ALG_MERGESCORES_FLOW;
  algs_to_dts[ALG_MERGESCORES_FLOW] = DT_MERGESCORES_FLOW;
  dts_to_algs[DT_MERGESCORES_DAY-1000] = ALG_MERGESCORES_DAY;
  algs_to_dts[ALG_MERGESCORES_DAY] = DT_MERGESCORES_DAY;
  dts_to_algs[DT_MERGESCORES_WEEK-1000] = ALG_MERGESCORES_WEEK;
  algs_to_dts[ALG_MERGESCORES_WEEK] = DT_MERGESCORES_WEEK;
  dts_to_algs[DT_SIMPLE_STAT_SCORER-1000] = ALG_SIMPLE_STAT_SCORER;
  algs_to_dts[ALG_SIMPLE_STAT_SCORER] = DT_SIMPLE_STAT_SCORER;
  dts_to_algs[DT_URL_FEATURES-1000] = ALG_URL_FEATURES;
  algs_to_dts[ALG_URL_FEATURES] = DT_URL_FEATURES;
  dts_to_algs[DT_URL_FEATURES_SCORE-1000] = ALG_URL_FEATURES_SCORE;
  algs_to_dts[ALG_URL_FEATURES_SCORE] = DT_URL_FEATURES_SCORE;
  dts_to_algs[DT_LOGON_FEATURES-1000] = ALG_LOGON_FEATURES;
  algs_to_dts[ALG_LOGON_FEATURES] = DT_LOGON_FEATURES;
  dts_to_algs[DT_LOGON_FEATURES_SCORE-1000] = ALG_LOGON_FEATURES_SCORE;
  algs_to_dts[ALG_LOGON_FEATURES_SCORE] = DT_LOGON_FEATURES_SCORE;
  dts_to_algs[DT_PRINTER_FEATURES-1000] = ALG_PRINTER_FEATURES;
  algs_to_dts[ALG_PRINTER_FEATURES] = DT_PRINTER_FEATURES;
  dts_to_algs[DT_PRINTER_FEATURES_SCORE-1000] = ALG_PRINTER_FEATURES_SCORE;
  algs_to_dts[ALG_PRINTER_FEATURES_SCORE] = DT_PRINTER_FEATURES_SCORE;
  dts_to_algs[DT_DEVICE_FEATURES-1000] = ALG_DEVICE_FEATURES;
  algs_to_dts[ALG_DEVICE_FEATURES] = DT_DEVICE_FEATURES;
  dts_to_algs[DT_DEVICE_FEATURES_SCORE-1000] = ALG_DEVICE_FEATURES_SCORE;
  algs_to_dts[ALG_DEVICE_FEATURES_SCORE] = DT_DEVICE_FEATURES_SCORE;
  dts_to_algs[DT_EMAIL_FEATURES-1000] = ALG_EMAIL_FEATURES;
  algs_to_dts[ALG_EMAIL_FEATURES] = DT_EMAIL_FEATURES;
  dts_to_algs[DT_EMAIL_FEATURES_SCORE-1000] = ALG_EMAIL_FEATURES_SCORE;
  algs_to_dts[ALG_EMAIL_FEATURES_SCORE] = DT_EMAIL_FEATURES_SCORE;
  dts_to_algs[DT_FILE_FEATURES-1000] = ALG_FILE_FEATURES;
  algs_to_dts[ALG_FILE_FEATURES] = DT_FILE_FEATURES;
  dts_to_algs[DT_FILE_FEATURES_SCORE-1000] = ALG_FILE_FEATURES_SCORE;
  algs_to_dts[ALG_FILE_FEATURES_SCORE] = DT_FILE_FEATURES_SCORE;
  dts_to_algs[DT_OTHER_FEATURE_SCORE-1000] = ALG_OTHER_FEATURE_SCORE;
  algs_to_dts[ALG_OTHER_FEATURE_SCORE] = DT_OTHER_FEATURE_SCORE;
  dts_to_algs[DT_URL_UPLOAD_SCORE-1000] = ALG_URL_UPLOAD_SCORE;
  algs_to_dts[ALG_URL_UPLOAD_SCORE] = DT_URL_UPLOAD_SCORE;
  dts_to_algs[DT_URL_DOWNLOAD_SCORE-1000] = ALG_URL_DOWNLOAD_SCORE;
  algs_to_dts[ALG_URL_DOWNLOAD_SCORE] = DT_URL_DOWNLOAD_SCORE;
  dts_to_algs[DT_URL_BLACKLIST_VISITS_SCORE-1000] = ALG_URL_BLACKLIST_VISITS_SCORE;
  algs_to_dts[ALG_URL_BLACKLIST_VISITS_SCORE] = DT_URL_BLACKLIST_VISITS_SCORE;
  dts_to_algs[DT_URL_DISTINCT_BLACKLIST_SCORE-1000] = ALG_URL_DISTINCT_BLACKLIST_SCORE;
  algs_to_dts[ALG_URL_DISTINCT_BLACKLIST_SCORE] = DT_URL_DISTINCT_BLACKLIST_SCORE;
  dts_to_algs[DT_URL_DOMAINS_PER_USER_SCORE-1000] = ALG_URL_DOMAINS_PER_USER_SCORE;
  algs_to_dts[ALG_URL_DOMAINS_PER_USER_SCORE] = DT_URL_DOMAINS_PER_USER_SCORE;
  dts_to_algs[DT_LOGON_SCORE-1000] = ALG_LOGON_SCORE;
  algs_to_dts[ALG_LOGON_SCORE] = DT_LOGON_SCORE;
  dts_to_algs[DT_LOGON_WORKSTATION_SCORE-1000] = ALG_LOGON_WORKSTATION_SCORE;
  algs_to_dts[ALG_LOGON_WORKSTATION_SCORE] = DT_LOGON_WORKSTATION_SCORE;
  dts_to_algs[DT_LOGON_ANOMALOUS_WORKSTATION_COUNT-1000] = ALG_LOGON_ANOMALOUS_WORKSTATION_COUNT;
  algs_to_dts[ALG_LOGON_ANOMALOUS_WORKSTATION_COUNT] = DT_LOGON_ANOMALOUS_WORKSTATION_COUNT;
  dts_to_algs[DT_PRINTER_NUMBER_OF_JOBS_SCORE-1000] = ALG_PRINTER_NUMBER_OF_JOBS_SCORE;
  algs_to_dts[ALG_PRINTER_NUMBER_OF_JOBS_SCORE] = DT_PRINTER_NUMBER_OF_JOBS_SCORE;
  dts_to_algs[DT_PRINTER_DISTINCT_PRINTER_SCORE-1000] = ALG_PRINTER_DISTINCT_PRINTER_SCORE;
  algs_to_dts[ALG_PRINTER_DISTINCT_PRINTER_SCORE] = DT_PRINTER_DISTINCT_PRINTER_SCORE;
  dts_to_algs[DT_PRINTER_WORKSTATION_SCORE-1000] = ALG_PRINTER_WORKSTATION_SCORE;
  algs_to_dts[ALG_PRINTER_WORKSTATION_SCORE] = DT_PRINTER_WORKSTATION_SCORE;
  dts_to_algs[DT_PRINTER_PER_USER_SCORE-1000] = ALG_PRINTER_PER_USER_SCORE;
  algs_to_dts[ALG_PRINTER_PER_USER_SCORE] = DT_PRINTER_PER_USER_SCORE;
  dts_to_algs[DT_EMAIL_RCVD_NUMBER_VIEWED_SCORE-1000] = ALG_EMAIL_RCVD_NUMBER_VIEWED_SCORE;
  algs_to_dts[ALG_EMAIL_RCVD_NUMBER_VIEWED_SCORE] = DT_EMAIL_RCVD_NUMBER_VIEWED_SCORE;
  dts_to_algs[DT_EMAIL_SENT_NUMBER_SENT_SCORE-1000] = ALG_EMAIL_SENT_NUMBER_SENT_SCORE;
  algs_to_dts[ALG_EMAIL_SENT_NUMBER_SENT_SCORE] = DT_EMAIL_SENT_NUMBER_SENT_SCORE;
  dts_to_algs[DT_FILE_REMOVABLE_ACCESS_SCORE-1000] = ALG_FILE_REMOVABLE_ACCESS_SCORE;
  algs_to_dts[ALG_FILE_REMOVABLE_ACCESS_SCORE] = DT_FILE_REMOVABLE_ACCESS_SCORE;
  dts_to_algs[DT_FILE_REMOVABLE_COPY_TO_SCORE-1000] = ALG_FILE_REMOVABLE_COPY_TO_SCORE;
  algs_to_dts[ALG_FILE_REMOVABLE_COPY_TO_SCORE] = DT_FILE_REMOVABLE_COPY_TO_SCORE;
  dts_to_algs[DT_FILE_REMOVABLE_COPY_FROM_SCORE-1000] = ALG_FILE_REMOVABLE_COPY_FROM_SCORE;
  algs_to_dts[ALG_FILE_REMOVABLE_COPY_FROM_SCORE] = DT_FILE_REMOVABLE_COPY_FROM_SCORE;
  dts_to_algs[DT_FILE_NUMBER_CREATED_SCORE-1000] = ALG_FILE_NUMBER_CREATED_SCORE;
  algs_to_dts[ALG_FILE_NUMBER_CREATED_SCORE] = DT_FILE_NUMBER_CREATED_SCORE;
  dts_to_algs[DT_FILE_FOLDER_CREATED_SCORE-1000] = ALG_FILE_FOLDER_CREATED_SCORE;
  algs_to_dts[ALG_FILE_FOLDER_CREATED_SCORE] = DT_FILE_FOLDER_CREATED_SCORE;
}

inline int64_t
alg_to_dt(int64_t alg) {
  if(alg < 500 && alg >= 0)
    return algs_to_dts[alg];
  else
    return 0;
}

inline int64_t
dt_to_alg(int64_t dt) {
  if(dt - 1000 < 500 && dt - 1000 >= 0)
    return dts_to_algs[dt-1000];
  else
    return 0;
}

inline const char *
get_string_from_alg(int64_t alg) {
  if(alg < 500 && alg >= 0)
    return algtype_strings[alg];
  else
    return "";
}

void
free_algs_to_dts() {
  free(dts_to_algs);
  free(algs_to_dts);
}
